import { getContractPrincipal, getRuntimeConfig } from './shared/runtime-config';

const runtime = getRuntimeConfig();
const CONTRACT_ADDRESS = runtime.contractAddress;
const CONTRACT_NAME = runtime.contractName;
const NETWORK_API = runtime.stacksApiUrl;
const CONTRACT_PRINCIPAL = getContractPrincipal(runtime);

console.log("=".repeat(70));
console.log("MAINNET TRANSACTION TESTING SUITE");
console.log("=".repeat(70));
console.log();
console.log("Contract:", CONTRACT_PRINCIPAL);
console.log("Network:", NETWORK_API);
console.log("Stage:", runtime.stage);
console.log("Stacks network:", runtime.stacksNetwork);
console.log();

console.log("PLANNED TEST TRANSACTIONS:");
console.log();
console.log("1. Create Habit - Valid (0.02 STX stake)");
console.log("   - Test minimum stake amount");
console.log("   - Verify habit creation and ID assignment");
console.log();
console.log("2. Create Habit - Higher Stake (1.0 STX)");
console.log("   - Test above-minimum stake");
console.log("   - Verify multiple habits per user");
console.log();
console.log("3. Check-in - First Day");
console.log("   - Test initial check-in");
console.log("   - Verify streak starts at 1");
console.log();
console.log("4. Get Habit - Read-only Query");
console.log("   - Test read-only function");
console.log("   - Verify data retrieval");
console.log();
console.log("5. Get User Habits - Read-only Query");
console.log("   - Test user habit list");
console.log("   - Verify habit IDs returned");
console.log();
console.log("6. Get Pool Balance - Read-only Query");
console.log("   - Test pool balance query");
console.log("   - Should be 0 initially");
console.log();
console.log("7. Get User Stats - Read-only Query");
console.log("   - Test aggregated stats");
console.log("   - Verify habit count");
console.log();
console.log("8. Check-in - Second Day (After 144 blocks)");
console.log("   - Test consecutive check-in");
console.log("   - Verify streak increment to 2");
console.log();
console.log("=".repeat(70));
console.log();
console.log("EXECUTION INSTRUCTIONS:");
console.log();
console.log("Use Clarinet console for manual transaction execution:");
console.log("  $ clarinet console --mainnet");
console.log();
console.log("Or use Stacks wallet directly for each transaction.");
console.log();
console.log("=".repeat(70));
