const CONTRACT_ADDRESS = "SP1M46W6CVGAMH3ZJD3TKMY5KCY48HWAZK0DYG193";
const CONTRACT_NAME = "habit-tracker";
const NETWORK_API = "https://api.mainnet.hiro.so";

console.log("=".repeat(70));
console.log("MAINNET TRANSACTION TESTING SUITE");
console.log("=".repeat(70));
console.log();
console.log("Contract:", `${CONTRACT_ADDRESS}.${CONTRACT_NAME}`);
console.log("Network:", NETWORK_API);
console.log();

console.log("PLANNED TEST TRANSACTIONS:");
console.log();
console.log("1. Create Habit - Valid (0.1 STX stake)");
console.log("   - Test minimum stake amount");
console.log("   - Verify habit creation and ID assignment");
console.log();
console.log("2. Create Habit - Higher Stake (1.0 STX)");
console.log("   - Test above-minimum stake");
console.log("   - Verify multiple habits per user");
console.log();
console.log("3. Check-in - First Day");
console.log("   - Test initial check-in");
console.log("   - Verify streak starts at 1");
console.log();
console.log("4. Get Habit - Read-only Query");
console.log("   - Test read-only function");
console.log("   - Verify data retrieval");
console.log();
console.log("5. Get User Habits - Read-only Query");
console.log("   - Test user habit list");
console.log("   - Verify habit IDs returned");
console.log();
console.log("6. Get Forfeited Pool Balance - Read-only Query");
console.log("   - Test pool balance query");
console.log("   - Should be 0 initially");
console.log();
console.log("7. Get User Stats - Read-only Query");
console.log("   - Test aggregated stats");
console.log("   - Verify habit count");
console.log();
console.log("8. Check-in - Second Day (After 144 blocks)");
console.log("   - Test consecutive check-in");
console.log("   - Verify streak increment to 2");
console.log();
console.log("=".repeat(70));
console.log();
console.log("EXECUTION INSTRUCTIONS:");
console.log();
console.log("Use Clarinet console for manual transaction execution:");
console.log("  $ clarinet console --mainnet");
console.log();
console.log("Or use Stacks wallet directly for each transaction.");
console.log();
console.log("=".repeat(70));
